/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/race/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the race for the athlete's active plan, or 404 if none is set */
        get: operations["getApiRaceCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiPlanDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotently regenerate the active plan from its template — overwrites edits */
        post: operations["postApiPlanRegenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putApiPlanId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiActivities"];
        put?: never;
        /** @description Upsert an activity (e.g. parsed from a .FIT file) and re-match its date's planned workout */
        post: operations["postApiActivities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All available training plan templates */
        get: operations["getApiTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A template's metadata + workout-by-day preview (no dates) */
        get: operations["getApiTemplatesKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All training plans for the athlete, with race details and active flag */
        get: operations["getApiPlans"];
        put?: never;
        /** @description Create a race + training_plan from a template, expand workouts, set active */
        post: operations["postApiPlans"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Set this plan as the athlete's active plan */
        post: operations["postApiPlansIdActivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a plan (and its race, cascading to workouts + matches) */
        delete: operations["deleteApiPlansId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityView */
        ActivityView: {
            /** Format: int64 */
            id: number;
            source: string;
            externalId: string;
            startedAt: string;
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            movingSeconds: number;
            /** Format: int32 */
            elevationGainM?: number;
            /** Format: int32 */
            avgHr?: number;
            activityType: string;
            name?: string;
        };
        /** ApiError */
        ApiError: {
            message: string;
        };
        /** CreateActivityRequest */
        CreateActivityRequest: {
            source: string;
            externalId: string;
            startedAt: string;
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            movingSeconds: number;
            /** Format: int32 */
            elevationGainM?: number;
            /** Format: int32 */
            avgHr?: number;
            activityType: string;
            name?: string;
        };
        /** CreateActivityResponse */
        CreateActivityResponse: {
            /** Format: int64 */
            activityId: number;
            duplicate: boolean;
            /** Format: int64 */
            matchedPlannedWorkoutId?: number;
            matchStatus?: string;
        };
        /** CreatePlanRequest */
        CreatePlanRequest: {
            templateKey: string;
            raceName: string;
            /** Format: date */
            raceDate: string;
            location?: string;
            /** Format: int32 */
            distanceM?: number;
            /** Format: int32 */
            vertM?: number;
            notes?: string;
        };
        /** CreatePlanResponse */
        CreatePlanResponse: {
            /** Format: int64 */
            planId: number;
            /** Format: int64 */
            raceId: number;
            /** Format: int32 */
            workoutsInserted: number;
        };
        /** OkResponse */
        OkResponse: {
            ok: boolean;
        };
        /** PlanSummaryView */
        PlanSummaryView: {
            /** Format: int64 */
            planId: number;
            /** Format: int64 */
            raceId: number;
            templateKey: string;
            templateName?: string;
            raceName: string;
            /** Format: date */
            raceDate: string;
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            vertM: number;
            location?: string;
            /** Format: int32 */
            workoutCount: number;
            generatedAt: string;
            isActive: boolean;
        };
        /** PlannedWorkoutView */
        PlannedWorkoutView: {
            /** Format: int64 */
            id: number;
            /** Format: date */
            date: string;
            type: string;
            /** Format: int32 */
            targetDistanceM?: number;
            /** Format: int32 */
            targetDurationS?: number;
            /** Format: int32 */
            targetVertM?: number;
            intensity?: string;
            notes?: string;
            matchStatus: string;
            /** Format: int64 */
            matchedActivityId?: number;
        };
        /** Race */
        Race: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: date */
            raceDate: string;
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            vertM: number;
            location?: string;
            notes?: string;
        };
        /** RegenerateResponse */
        RegenerateResponse: {
            /** Format: int64 */
            planId: number;
            /** Format: int32 */
            workoutsInserted: number;
        };
        /** TemplateDetailView */
        TemplateDetailView: {
            summary: components["schemas"]["TemplateSummary"];
            workouts?: components["schemas"]["TemplateWorkoutView"][];
        };
        /** TemplateSummary */
        TemplateSummary: {
            key: string;
            name: string;
            description: string;
            raceCategory: string;
            terrain: string;
            level: string;
            /** Format: int32 */
            weeks: number;
            /** Format: int32 */
            defaultDistanceM: number;
            /** Format: int32 */
            defaultVertM: number;
        };
        /** TemplateWorkoutView */
        TemplateWorkoutView: {
            /** Format: int32 */
            weeksOut: number;
            /** Format: int32 */
            dayOfWeek: number;
            type: string;
            /** Format: int32 */
            targetDistanceM?: number;
            /** Format: int32 */
            targetDurationS?: number;
            /** Format: int32 */
            targetVertM?: number;
            intensity?: string;
            notes?: string;
        };
        /** WorkoutDetailView */
        WorkoutDetailView: {
            planned: components["schemas"]["PlannedWorkoutView"];
            matchedActivity?: components["schemas"]["ActivityView"];
        };
        /** WorkoutEdit */
        WorkoutEdit: {
            type: string;
            /** Format: int32 */
            targetDistanceM?: number;
            /** Format: int32 */
            targetDurationS?: number;
            /** Format: int32 */
            targetVertM?: number;
            intensity?: string;
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiRaceCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Race"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getApiPlan: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutView"][];
                };
            };
            /** @description Invalid value for: query parameter from, Invalid value for: query parameter to */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getApiPlanDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutDetailView"];
                };
            };
            /** @description Invalid value for: path parameter date */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postApiPlanRegenerate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    putApiPlanId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutEdit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutView"];
                };
            };
            /** @description Invalid value for: path parameter id, Invalid value for: body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getApiActivities: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityView"][];
                };
            };
            /** @description Invalid value for: query parameter limit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postApiActivities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateActivityResponse"];
                };
            };
            /** @description Invalid value for: body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getApiTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSummary"][];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getApiTemplatesKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDetailView"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getApiPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryView"][];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postApiPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlanResponse"];
                };
            };
            /** @description Invalid value for: body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postApiPlansIdActivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Invalid value for: path parameter id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteApiPlansId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Invalid value for: path parameter id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
