/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesKeyRouteImport } from './routes/templates.$key'
import { Route as PlanDateRouteImport } from './routes/plan.$date'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesKeyRoute = TemplatesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => TemplatesRoute,
} as any)
const PlanDateRoute = PlanDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => PlanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/plan': typeof PlanRouteWithChildren
  '/plans': typeof PlansRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/upload': typeof UploadRoute
  '/plan/$date': typeof PlanDateRoute
  '/templates/$key': typeof TemplatesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/plan': typeof PlanRouteWithChildren
  '/plans': typeof PlansRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/upload': typeof UploadRoute
  '/plan/$date': typeof PlanDateRoute
  '/templates/$key': typeof TemplatesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/plan': typeof PlanRouteWithChildren
  '/plans': typeof PlansRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/upload': typeof UploadRoute
  '/plan/$date': typeof PlanDateRoute
  '/templates/$key': typeof TemplatesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/plan'
    | '/plans'
    | '/settings'
    | '/templates'
    | '/upload'
    | '/plan/$date'
    | '/templates/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/plan'
    | '/plans'
    | '/settings'
    | '/templates'
    | '/upload'
    | '/plan/$date'
    | '/templates/$key'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/plan'
    | '/plans'
    | '/settings'
    | '/templates'
    | '/upload'
    | '/plan/$date'
    | '/templates/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  PlanRoute: typeof PlanRouteWithChildren
  PlansRoute: typeof PlansRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$key': {
      id: '/templates/$key'
      path: '/$key'
      fullPath: '/templates/$key'
      preLoaderRoute: typeof TemplatesKeyRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/plan/$date': {
      id: '/plan/$date'
      path: '/$date'
      fullPath: '/plan/$date'
      preLoaderRoute: typeof PlanDateRouteImport
      parentRoute: typeof PlanRoute
    }
  }
}

interface PlanRouteChildren {
  PlanDateRoute: typeof PlanDateRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanDateRoute: PlanDateRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

interface TemplatesRouteChildren {
  TemplatesKeyRoute: typeof TemplatesKeyRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesKeyRoute: TemplatesKeyRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  PlanRoute: PlanRouteWithChildren,
  PlansRoute: PlansRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
